/* Registry of built-in examples.

   Each carries a bilingual "how it works" written by hand, and names the
   relation it exploits - so the visualizer keeps pointing back at the compass
   instead of drifting into a separate pile of patterns. */

import type { VizExample } from '../types';
import {
  buildBFS, buildBinarySearch, buildDFS, buildReverseLinkedList,
  buildTrappingRainWater, buildTwoSum, buildValidParentheses,
} from './index';

export const VIZ_EXAMPLES: VizExample[] = [
  {key:'trapping-rain-water', rel:'order', name:{vi:'Hứng nước mưa',en:'Trapping Rain Water'}, viz:buildTrappingRainWater(),
   expl:{vi:{intuition:'Nước trên một cột do bức tường cao gần nhất mỗi bên quyết định. Một ngăn xếp giữ các chiều cao giảm dần chính là bộ nhớ những "tường trái" ứng viên, nên bạn không quét lại.',approach:['Quét các cột từ trái sang phải, giữ ngăn xếp chỉ số có chiều cao giảm dần.','Gặp cột cao hơn → nó là tường phải: lấy đáy ra và tính nước bị giữ.','Bề rộng × chiều cao bị chặn cộng vào kết quả; đẩy mỗi chỉ số làm tường trái tương lai.'],why:'Mỗi cột được đẩy và lấy ra tối đa một lần → O(n). Ngăn xếp biến việc "nhìn trái, nhìn phải" 2 chiều thành một lượt duy nhất — đây là quan hệ THỨ TỰ (đơn điệu).',pitfalls:['Dừng khi ngăn xếp rỗng sau khi pop — không có tường trái thì không có bồn chứa.','So sánh chặt (height[i] > top) để giữ tính giảm dần.']},en:{intuition:'Water over a bar is decided by the nearest taller wall on each side. A stack of decreasing heights remembers exactly those candidate left walls, so you never rescan.',approach:['Scan bars left to right, keeping a stack of indices with decreasing heights.','When a taller bar appears it is a right wall: pop the bottom and settle the water it traps.','Width × bounded-height adds to the result; push each index as a future left wall.'],why:'Each bar is pushed and popped at most once → O(n). The stack turns a 2-D "look left and right" into one pass — the ORDER (monotonic) relation.',pitfalls:['Break when the stack becomes empty after a pop — no left wall means no basin.','Compare strictly (height[i] > top) to keep heights decreasing.']}}},
  {key:'binary-search', rel:'order', name:{vi:'Tìm kiếm nhị phân',en:'Binary Search'}, viz:buildBinarySearch(),
   expl:{vi:{intuition:'Mảng đã sắp xếp là một trục đơn điệu: một phép so sánh ở giữa cho biết nửa nào chắc chắn không chứa mục tiêu, nên bạn vứt cả nửa đó.',approach:['Giữ khoảng [left, right]; nhìn phần tử giữa.','Nếu bằng mục tiêu → xong.','Nếu nhỏ hơn → đáp án ở bên phải; ngược lại bên trái. Chia đôi và lặp.'],why:'Mỗi bước bỏ đi một nửa khoảng còn lại → O(log n). Đây là bản chất của quan hệ THỨ TỰ.',pitfalls:['Dùng left + (right−left)/2 để tránh tràn số.','Lặp khi left ≤ right, và nhảy qua mid (mid±1) nếu không sẽ lặp vô hạn.']},en:{intuition:'A sorted array is a monotonic axis: one comparison at the middle tells you which half cannot contain the target, so you discard it wholesale.',approach:['Keep a [left, right] range; look at the middle.','If it equals the target, done.','If it is smaller, the answer is to the right; otherwise to the left. Halve and repeat.'],why:'Each step throws away half the remaining range → O(log n). This is the ORDER relation at its purest.',pitfalls:['Use left + (right−left)/2 to avoid overflow.','Loop while left ≤ right, and move past mid (mid±1) or you can loop forever.']}}},
  {key:'two-sum', rel:'identity', name:{vi:'Two Sum',en:'Two Sum'}, viz:buildTwoSum(),
   expl:{vi:{intuition:'Bạn không cần thứ tự — chỉ cần nhận ra một giá trị đã gặp. Hashmap trả lời "đã thấy phần bù chưa?" trong O(1).',approach:['Với mỗi số, tính phần bù = target − num.','Nếu phần bù đã có trong map → tìm được cặp.','Nếu chưa, lưu num → chỉ số rồi đi tiếp.'],why:'Mỗi phần tử được chèn và tra một lần → O(n). Chỉ dùng quan hệ DANH TÍNH (đã thấy hay chưa) — thứ tự vô nghĩa.',pitfalls:['Kiểm tra phần bù TRƯỚC khi chèn số hiện tại, nếu không một giá trị có thể tự khớp chính nó.','Lưu chỉ số, không chỉ sự tồn tại, để trả về vị trí.']},en:{intuition:"You don't need order — you only need to recognise a value you've seen. A hashmap answers 'have I seen the complement?' in O(1).",approach:['For each number, compute the complement target − num.','If the complement is already in the map, you found the pair.','Otherwise store num → index and move on.'],why:'Each element is inserted and looked up once → O(n). Only the IDENTITY relation (seen-or-not) is used — order is irrelevant.',pitfalls:['Check the complement before inserting the current number, or a value could match itself.','Store the index, not just presence, to return positions.']}}},
  {key:'valid-parentheses', rel:'traverse', name:{vi:'Ngoặc hợp lệ',en:'Valid Parentheses'}, viz:buildValidParentheses(),
   expl:{vi:{intuition:'Chỉ dấu mở chưa khớp GẦN NHẤT mới được đóng tiếp — nhu cầu "vào sau, ra trước" đó chính là một ngăn xếp.',approach:['Đẩy mọi dấu mở vào ngăn xếp.','Gặp dấu đóng, đỉnh phải là dấu mở tương ứng; lấy ra.','Hợp lệ ⇔ không có sai khớp nào và ngăn xếp rỗng ở cuối.'],why:'Mỗi ký tự được đẩy/lấy tối đa một lần → O(n). Ngăn xếp mã hóa sẵn cấu trúc lồng nhau.',pitfalls:['Dấu đóng gặp ngăn xếp rỗng là ngay lập tức không hợp lệ.','Còn dấu mở thừa ở cuối nghĩa là không cân bằng.']},en:{intuition:'Only the most recent unmatched opener can be closed next — that "last in, first out" need is exactly a stack.',approach:['Push every opening bracket.','On a closing bracket, the top must be its matching opener; pop it.','Valid iff nothing mismatches and the stack ends empty.'],why:'Each character is pushed/popped at most once → O(n). The stack encodes the nesting structure for free.',pitfalls:['A closing bracket with an empty stack is immediately invalid.','Leftover openers at the end mean unbalanced.']}}},
  {key:'reverse-linked-list', rel:'traverse', name:{vi:'Đảo danh sách liên kết',en:'Reverse Linked List'}, viz:buildReverseLinkedList(),
   expl:{vi:{intuition:'Đảo từng liên kết một, nhưng nhớ nút kế trước đã, để không mất phần đuôi.',approach:['Giữ prev (phần đã đảo), curr (nút đang xử lý), next (nhìn trước).','Trỏ curr ngược về prev, rồi trượt cả ba tiến lên.','Khi curr là null, prev là đầu mới.'],why:'Một lượt, O(1) bộ nhớ phụ — bạn viết lại con trỏ tại chỗ.',pitfalls:['Lưu next TRƯỚC khi viết lại curr→next, nếu không sẽ mất phần còn lại.','Trả về prev, không phải curr (curr là null ở cuối).']},en:{intuition:"Reverse the links one node at a time, but remember the next node first so you don't lose the tail.",approach:['Keep prev (reversed part), curr (node under work), next (lookahead).','Point curr back at prev, then slide all three forward.','When curr is null, prev is the new head.'],why:'One pass, O(1) extra memory — you rewrite pointers in place.',pitfalls:['Save next before rewriting curr→next, or the rest of the list is lost.','Return prev, not curr (which is null at the end).']}}},
  {key:'bfs', rel:'traverse', name:{vi:'BFS — duyệt theo chiều rộng',en:'Breadth-First Search'}, viz:buildBFS(),
   expl:{vi:{intuition:'Hàng đợi FIFO khám phá đồ thị theo từng vòng cùng khoảng cách từ điểm bắt đầu — nên lần đầu chạm một nút là theo đường ngắn nhất (số cạnh).',approach:['Đưa nút bắt đầu vào hàng đợi và đánh dấu đã thăm.','Lặp: lấy một nút ra, đưa các hàng xóm chưa thăm vào.','Thứ tự lấy ra chính là thứ tự BFS.'],why:'Mỗi đỉnh và cạnh được chạm một lần → O(V+E). Hàng đợi bảo đảm thứ tự theo tầng.',pitfalls:['Đánh dấu đã thăm khi ĐƯA VÀO (không phải khi lấy ra) để tránh trùng trong hàng đợi.','Cạnh vô hướng phải đi được cả hai chiều.']},en:{intuition:'A FIFO queue explores the graph in rings of equal distance from the start — so the first time you reach a node is by a shortest path (in edges).',approach:['Enqueue the start and mark it visited.','Repeatedly dequeue a node and enqueue its unvisited neighbours.','The dequeue order is the BFS order.'],why:'Every vertex and edge is touched once → O(V+E). The queue guarantees level-by-level order.',pitfalls:['Mark visited when enqueuing (not dequeuing) to avoid duplicates in the queue.','Undirected edges must be walkable both ways.']}}},
  {key:'dfs', rel:'traverse', name:{vi:'DFS — duyệt theo chiều sâu',en:'Depth-First Search'}, viz:buildDFS(),
   expl:{vi:{intuition:'Ngăn xếp LIFO lao sâu hết mức trước khi lùi lại — kỷ luật ngược với hàng đợi của BFS.',approach:['Đẩy nút bắt đầu.','Lấy một nút ra; nếu chưa thăm thì thăm và đẩy các hàng xóm chưa thăm.','Tiếp tục cho tới khi ngăn xếp rỗng.'],why:'Mỗi đỉnh và cạnh được chạm một lần → O(V+E). Ngăn xếp mã hóa thứ tự "đi sâu trước".',pitfalls:['Kiểm tra đã thăm khi LẤY RA (một nút có thể bị đẩy nhiều lần trước khi được thăm lần đầu).','Thứ tự đẩy hàng xóm sẽ lật thứ tự thăm.']},en:{intuition:"A LIFO stack dives as deep as possible before backing up — the opposite discipline to BFS's queue.",approach:['Push the start.','Pop a node; if unvisited, visit it and push its unvisited neighbours.','Continue until the stack is empty.'],why:'Every vertex and edge is touched once → O(V+E). The stack encodes the "go deeper first" order.',pitfalls:['Check visited on pop (a node can be pushed several times before it is first visited).','Neighbour push order flips the visit order.']}}}
];
